### ISSUE TITLE
Unable to clone "could not clone https://github.com/envoyproxy/envoy.git: signal: killed fatal: early EOF"

### ISSUE THREAD

**Issue by Cgopikri** [GoogleCloudPlatform/service-extensions#110]
## Expected Behavior
clone should happen when running this command "buf -v generate \
  https://github.com/envoyproxy/envoy.git#subdir=api \
  --path envoy/service/ext_proc/v3/external_processor.proto \
  --include-imports"

## Actual Behavior
ended with this error "could not clone https://github.com/envoyproxy/envoy.git: signal: killed fatal: early EOF"

## Steps to Reproduce the Problem

1.
1.
1.

## Specifications

- Version:
- Platform:

**Comment by martijneken** [comment]
Context: this is part of the Callouts quick start documentation here: https://github.com/GoogleCloudPlatform/service-extensions/blob/main/docs/python/readme/quick_start.rst

FYI @rshriram

**Comment by rshriram** [comment]
sorry for the late response. Is this reproducible @Cgopikri ? [cc @jstraceski ]

**Comment by jstraceski** [comment]
Hmm, I can't seem to reproduce this issue.
Could you run again with the `--debug` and `--verbose` flags?

```
buf -v generate https://github.com/envoyproxy/envoy.git#subdir=api --path envoy/service/ext_proc/v3/external_processor.proto --include-imports --verbose --debug
```
